### ISSUE TITLE
User signup/login

### ISSUE THREAD

**Issue by ubaldop** [Stamplay/stamplay-nodejs-sdk#1]
Will this **stamplay-nodejs-sdk** provide API calls to perform users signup/login operations?

I mean the flavor like the one documented in the standard [Stamplay JS SDK](https://github.com/Stamplay/stamplay-js-sdk)?

```
// With Callback
  Stamplay.User
.login(credentials, function(err, res) {
  if(err) return console.log(err);
  console.log(res);
})

  // With Promise
  Stamplay.User
.login(credentials)
  .then(function(res){
// Success
  }, function(err) {
// Handle Error
  });
```

If so, will be these functions bundled with future releases of this node API?

Thank you!

P.S.: Stamplay is a very cool service :)

**Comment by criroselli** [comment]
Hey, 
thank you for your appreciation!
Can I ask you what is the scenario when signup/login is are useful in the your server app ? 

:smile:

**Comment by ubaldop** [comment]
Hi @criroselli,
I am playing with your platform to get confidence with it: basically I am implementing distributed batch processes, no frontend then, using Stamplay exclusively as persistence layer. 

Somehow I'd like to use Stamplay authorization exclusively to define ACLs for processes: each process can read/store specific data according to its role.

Maybe it's the wrong use case: I am basically doing exploration, so I'd miss the point.

Thank you again!

**Comment by criroselli** [comment]
Don't worry @P3trur0  
If you need help or anything else send me an email or write to me in our slack community.

:rocket:
